First import all necessairy modules. 

In [1]:
from preprocess import Preprocessor
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense
from keras.metrics import Accuracy, Precision, Recall
from message_encoder import *

The we load the data, preprocess it and then split it into Training and Test data. This may take a while. 

In [2]:
m_encoder = BERTEncoder()

pp = Preprocessor([i for i in range(745, 760)], m_encoder, logs_per_class=100, window_size=20, volatile=True)
train_data, test_data = pp.stratified_split()
X_train, y_train = zip(*train_data)
X_test, y_test = zip(*test_data)

X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)

Current log file: C:/Users/Askion/Documents/agmge/log-classification/data/CCI/CCLog-backup.745.log


parsing log file:   0%|          | 0/811279 [00:00<?, ?it/s]

annotating events:   0%|          | 0/807974 [00:00<?, ?it/s]

Current State counts:
  - 0 : 100
  - 3 : 100
  - 2 : 14
  - 1 : 4
Current log file: C:/Users/Askion/Documents/agmge/log-classification/data/CCI/CCLog-backup.746.log


parsing log file:   0%|          | 0/322863 [00:00<?, ?it/s]

annotating events:   0%|          | 0/314649 [00:00<?, ?it/s]

Current State counts:
  - 0 : 100
  - 3 : 100
  - 2 : 34
  - 1 : 10
Current log file: C:/Users/Askion/Documents/agmge/log-classification/data/CCI/CCLog-backup.747.log


parsing log file:   0%|          | 0/185821 [00:00<?, ?it/s]

annotating events:   0%|          | 0/178255 [00:00<?, ?it/s]

Current State counts:
  - 0 : 100
  - 3 : 100
  - 2 : 62
  - 1 : 10
Current log file: C:/Users/Askion/Documents/agmge/log-classification/data/CCI/CCLog-backup.748.log


parsing log file:   0%|          | 0/217424 [00:00<?, ?it/s]

annotating events:   0%|          | 0/207352 [00:00<?, ?it/s]

Current State counts:
  - 0 : 100
  - 3 : 100
  - 2 : 100
  - 1 : 19
Current log file: C:/Users/Askion/Documents/agmge/log-classification/data/CCI/CCLog-backup.749.log


parsing log file:   0%|          | 0/86349 [00:00<?, ?it/s]

annotating events:   0%|          | 0/76720 [00:00<?, ?it/s]

Current State counts:
  - 0 : 100
  - 3 : 100
  - 2 : 100
  - 1 : 37
Current log file: C:/Users/Askion/Documents/agmge/log-classification/data/CCI/CCLog-backup.750.log


parsing log file:   0%|          | 0/104128 [00:00<?, ?it/s]

annotating events:   0%|          | 0/103928 [00:00<?, ?it/s]

Current State counts:
  - 0 : 100
  - 3 : 100
  - 2 : 100
  - 1 : 55
Current log file: C:/Users/Askion/Documents/agmge/log-classification/data/CCI/CCLog-backup.751.log


parsing log file:   0%|          | 0/103334 [00:00<?, ?it/s]

annotating events:   0%|          | 0/103134 [00:00<?, ?it/s]

Current State counts:
  - 0 : 100
  - 3 : 100
  - 2 : 100
  - 1 : 73
Current log file: C:/Users/Askion/Documents/agmge/log-classification/data/CCI/CCLog-backup.752.log


parsing log file:   0%|          | 0/102980 [00:00<?, ?it/s]

annotating events:   0%|          | 0/102703 [00:00<?, ?it/s]

Current State counts:
  - 0 : 100
  - 3 : 100
  - 2 : 100
  - 1 : 91
Current log file: C:/Users/Askion/Documents/agmge/log-classification/data/CCI/CCLog-backup.753.log


parsing log file:   0%|          | 0/301697 [00:00<?, ?it/s]

annotating events:   0%|          | 0/253791 [00:00<?, ?it/s]

Current State counts:
  - 0 : 100
  - 3 : 100
  - 2 : 100
  - 1 : 100
All states have the desired log count


Now we define the LSTM model, train it and then print a summary.

In [4]:
# Build the model
lstm_layers = 50
epochs = 1000
model = Sequential()
model.add(LSTM(lstm_layers, input_shape=(pp.window_size, 20)))  # 50 units in LSTM layer
num_classes = len(set(y_train))  # Assuming labels are integers
model.add(Dense(num_classes, activation='softmax'))
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', 
              metrics=[
                  'accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=epochs, batch_size=32)

# Summary of the model
model.summary()

Epoch 1/1000
10/10 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.4324 - loss: 1.2322
Epoch 2/1000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5858 - loss: 1.0780
Epoch 3/1000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7032 - loss: 0.9948
Epoch 4/1000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7905 - loss: 0.9132
Epoch 5/1000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8600 - loss: 0.8365
Epoch 6/1000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8691 - loss: 0.7879
Epoch 7/1000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8889 - loss: 0.7208
Epoch 8/1000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8943 - loss: 0.6773
Epoch 9/1000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9100 - loss: 0.6525
Epoch 10/1000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9236 - loss: 0.6244
Epoch 11/1000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9143 - loss: 0.5923
Epoch 12/1000
10/10 ━━━━━━━━━━━━━━━━━━━━ 

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_1 (LSTM)                   │ (None, 50)             │        14,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │           204 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 43,214 (168.81 KB)

 Trainable params: 14,404 (56.27 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 28,810 (112.54 KB)

In [24]:
model.save(f"lstm_x{lstm_layers}_{epochs}.h5")

Then we test the model with the test data

In [6]:
test_loss = model.evaluate(X_test, y_test)
print(f"Test MSE: {test_loss}")

print()
results = model.evaluate(X_test, y_test, verbose=0)

for name, value in zip(model.metrics_names, results):
    print(f"{name}: {value:.4f}")



predictions = model.predict(X_test)

# Print a few predictions vs actuals
a = []
for i in range(80):
    a.append(np.argmax(predictions[i]) == y_test[i])
    print(predictions[i])
    # print(f"Predicted: {predictions[i]}, Actual: {y_test[i]}")

print(a.count(True))

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.0016
Test MSE: [0.0012323663104325533, 1.0]

loss: 0.0012
compile_metrics: 1.0000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
[9.9998462e-01 9.4564957e-06 2.7791764e-06 3.2070348e-06]
[9.9994743e-01 4.5357432e-05 6.4180986e-06 8.0982284e-07]
[1.3871414e-06 8.2120687e-07 3.2621210e-05 9.9996519e-01]
[1.8741754e-05 1.9420614e-04 9.9971241e-01 7.4650467e-05]
[9.9974889e-01 1.1471417e-04 1.1113990e-05 1.2531123e-04]
[7.2715983e-07 3.0281255e-04 9.9969232e-01 4.1287103e-06]
[4.6528280e-06 3.5423417e-07 1.2245214e-05 9.9998271e-01]
[1.7930557e-05 9.9929309e-01 6.8594940e-04 2.9950370e-06]
[2.3661498e-06 2.1341875e-04 9.9976164e-01 2.2602102e-05]
[1.9601359e-04 9.9980289e-01 6.4803430e-08 1.0994086e-06]
[9.99790490e-01 2.09472040e-04 5.10201126e-08 1.22241754e-08]
[5.7423138e-05 3.3350780e-08 1.4667035e-04 9.9979597e-01]
[9.99748886e-01 1.14750386e-04 1.11166710e-05 1.25332386e-04]
[3.4583762e-04 9.9965191e-01 3.4973880e-07 1.944280